### ISSUE TITLE
Request: Add Spleen.

### ISSUE THREAD

**Issue by 4goodapp** [Tecate/bitmap-fonts#11]
[Spleen](https://github.com/fcambus/spleen)
Spleen is a monospaced bitmap font available in 5 sizes:

5x8
8x16
12x24
16x32
32x64

https://github.com/fcambus/spleen

![image](https://user-images.githubusercontent.com/6249230/53281657-65560f80-3724-11e9-84c3-d8bb800ca1e5.png)

**Comment by Tecate** [comment]
Added spleen. Next time just put in a pull request and I'll merge it
