### ISSUE TITLE
update tamzen-font

### ISSUE THREAD

**Issue by sunaku** [Tecate/bitmap-fonts#3]
Hello,

Tamzen no longer has an uneven baseline at size 13:

![TamzenForPowerline7x13r.bdf](https://github.com/sunaku/tamzen-font/raw/master/png/TamzenForPowerline7x13r.png) ![TamzenForPowerline7x13b.bdf](https://github.com/sunaku/tamzen-font/raw/master/png/TamzenForPowerline7x13b.png)

Also, it would help if you could demo size 15 instead:

![TamzenForPowerline8x15r.bdf](https://github.com/sunaku/tamzen-font/raw/master/png/TamzenForPowerline8x15r.png) ![TamzenForPowerline8x15b.bdf](https://github.com/sunaku/tamzen-font/raw/master/png/TamzenForPowerline8x15b.png)

Because sizes 12 and 13 are the same as in Tamsyn 1.11; the rest differentiate Tamzen from Tamsyn.

Cheers.

**Comment by Tecate** [comment]
Finally got around to updating. Sorry it took so long.
